stages:
  - build
  - test
  - deploy

cache:
  key: maven-cache
  paths:
    - .m2/repository

build-job:
  stage: build
  tags:
    - yandex-vps-runner
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

integration-test:
  stage: test
  tags:
    - yandex-vps-runner
  dependencies:
    - build-job
  variables:
    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:6666/eventhub_db
  before_script:
    - docker compose down || true
    - docker compose up -d db
    - echo "Ждём БД на порту 6666..."
    - until pg_isready -h localhost -p 6666 -U postgres -d eventhub_db; do sleep 2; done
    - echo "БД готова!"
  script:
    - mvn test --no-transfer-progress
  after_script:
    - docker compose down -v || true
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    when: always
    expire_in: 1 day

deploy:
  stage: deploy
  tags:
    - yandex-vps-runner
  dependencies:
    - build-job
  script:
    - docker compose up -d --build
    - echo "Деплой завершён!"
  after_script:
    - |
      STATUS="❌"
      if [ $? -eq 0 ]; then STATUS="✅"; fi
      VERSION="${CI_COMMIT_SHORT_SHA}"
      if [ -n "$CI_COMMIT_TAG" ]; then VERSION="$CI_COMMIT_TAG"; fi
      
      MESSAGE="*${STATUS} Деплой EventHub*  
      Проект: _${CI_PROJECT_NAME}_ 
      Ветка: _${CI_COMMIT_REF_NAME}_  
      Версия: _${VERSION}_  
      Пайплайн: _${CI_PIPELINE_URL}_  
      Приложение: _ http://158.160.87.130:9999 _"
      
      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id=${TELEGRAM_CHAT_ID} \
              -d text="${MESSAGE}" \
              -d parse_mode=Markdown \
              -d disable_web_page_preview=true > /dev/null
  environment:
    name: production
    url: http://158.160.87.130:9999
#  when: manual
  only:
    - master