stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - yandex-vps-runner
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

integration-test:
  stage: test
  tags:
    - yandex-vps-runner
  dependencies:
    - build-job
  variables:
    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:6666/eventhub_db
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: postgres
  before_script:
    - docker compose down || true
    - docker compose up -d db
    - echo "Ждём БД на порту 6666..."
    - until pg_isready -h localhost -p 6666 -U postgres -d eventhub_db; do sleep 2; done
    - echo "БД готова!"
  script:
    - mvn test --no-transfer-progress
  after_script:
    - docker compose down -v || true
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    when: always
    expire_in: 1 day
