stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - yandex-vps-runner
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

integration-test:
  stage: test
  tags:
    - yandex-vps-runner
  dependencies:
    - build-job
  variables:
    SPRING_PROFILES_ACTIVE: docker
  before_script:
    - docker compose up -d db
    - echo "ждем бд"
    - until docker compose exec -T db pg_isready -U postgres -d eventhub_db; do sleep 2; done
    - echo "дождались"
  script:
    - mvn test
  after_script:
    - docker compose down -v || true
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    when: always
    expire_in: 1 day


