stages:
  - build
  - tests

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

integration-test:
  stage: tests
  dependencies:
    - build-job
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    SPRING_PROFILES_ACTIVE: docker
  before_script:
    - apt-get install -y docker.io
    - apt-get update && apt-get install -y docker-compose-plugin
    - docker info
    - docker compose up -d db
    - echo "ждем бд"
    - until docker compose exec -T db pg_isready -U postgres -d eventhub_db; do sleep 2; done
    - echo "дождались"
  script:
    - mvn test
  after_script:
    - docker compose down -v || true
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    when: always
    expire_in: 1 day


